

BASE:
 #log等级
 log_level: "debug"
 #扩展名
 log_extension: ".log"
 test:
#  url: "http://211.103.136.242:8064"
  url: "http://172.16.90.179:28082"
#  url: "http://172.16.90.164:9193"
  case_file: "testdata.xls"
  result_file: "testdata_res.xls"
  case_sheet: "美多商城接口测试"


email:
# smtpserver: "smtp.itcast.com"
# username: "wangxu@itcast.com"
# password: "FDSArewq1"
# receiver: "wangxu@itcast.com"
 smtpserver: "smtp.qq.com"
 username: "625797848@qq.com"
 password: "nnylbuehvbqebbed"
 receiver: "625797848@qq.com"
